# Generated by Django 3.1.7 on 2021-04-27 11:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(upload_to=main.models.file_name),
        ),
    ]
